CREATE BIGFILE TABLESPACE OLTP_USER DATAFILE
  '@dataSource.datafile.dir@/OLTP_USER' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
;

CREATE BIGFILE TABLESPACE OLTP_USER_ENCRYPTED DATAFILE
  '@dataSource.datafile.dir@/OLTP_USER_ENCRYPTED' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
ENCRYPTION USING 'AES192'
DEFAULT STORAGE(ENCRYPT)
;

CREATE BIGFILE TABLESPACE OLTP_USER_ARCHIVE DATAFILE
  '@dataSource.datafile.dir@/OLTP_USER_ARCHIVE' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
;

CREATE BIGFILE TABLESPACE OLTP_USER_ENCRYPTED_ARCHIVE DATAFILE
  '@dataSource.datafile.dir@/OLTP_USER_ENCRYPTED_ARCHIVE' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
ENCRYPTION USING 'AES192'
DEFAULT STORAGE(ENCRYPT)
;

